name: Build IPA
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild -scheme "Pépite" -configuration Release \
            -destination 'generic/platform=iOS' -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build
          ls -la build/Build/Products/Release-iphoneos/
          mkdir -p Payload
          cp -R "build/Build/Products/Release-iphoneos/Pépite "Payload/Pépite.app"
          ls -la "Payload/Pépite.app"
          zip -r app.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.ipa

